-H:+UnlockExperimentalVMOptions
-H:+ReportExceptionStackTraces
-H:ServiceLoaderFeatureExcludeServices=org.hibernate.bytecode.spi.BytecodeProvider
-H:ReflectionConfigurationResources=${.}/reflect-config.json
